using System;
using System.Collections.Generic;
using System.Text;

namespace NCurses.Core.Interop.SingleByteString
{
    internal interface ISingleByteStringWrapper<TSingleByteString> : INativeWrapper
    {
        //int addnstr(const char *str, int n);
        int addnstr(in TSingleByteString txt, int number);
        //int addstr(const char *str);
        int addstr(in TSingleByteString txt);
        //const char * curses_version(void);
        ref TSingleByteString curses_version();
        //int define_key(const char *definition, int keycode);
        int define_key(in TSingleByteString definition, int keycode);
        //int define_key(SCREEN* sp, const char *definition, int keycode);
        int define_key_sp(IntPtr screen, in TSingleByteString definition, int keycode);
        //char erasechar(void);
        TSingleByteString erasechar();
        //char erasechar_sp(SCREEN* sp);
        TSingleByteString erasechar_sp(IntPtr screen);
        //int getnstr(char *str, int n);
        int getnstr(ref TSingleByteString txt, int count);
        //int getstr(char *str);
        int getstr(ref TSingleByteString txt);
        //int instr(char *str);
        int innstr(ref TSingleByteString str, int n);
        //int insnstr(const char *str, int n);
        int insnstr(in TSingleByteString str, int n);
        //int insstr(const char *str);
        int insstr(in TSingleByteString str);
        //int instr(char *str);
        int instr(ref TSingleByteString str);
        //int key_defined(const char *definition);
        int key_defined(in TSingleByteString definition);
        //int key_defined(const char *definition);
        int key_defined_sp(IntPtr screen, in TSingleByteString definition);
        //char * keybound(int keycode, int count);
        ref TSingleByteString keybound(int keycode, int count);
        //char * keybound_sp(SCREEN* sp, int keycode, int count);
        ref TSingleByteString keybound_sp(IntPtr screen, int keycode, int count);
        //char *keyname(int c);
        ref TSingleByteString keyname(int c);
        //char *keyname_sp(SCREEN* sp, int c);
        ref TSingleByteString keyname_sp(IntPtr screen, int c);
        //char killchar(void);
        TSingleByteString killchar();
        //char killchar_sp(SCREEN* sp);
        TSingleByteString killchar_sp(IntPtr screen);
        //char *longname(void);
        ref TSingleByteString longname();
        //char *longname_sp(SCREEN* sp);
        ref TSingleByteString longname_sp(IntPtr screen);
        //int mvaddnstr(int y, int x, const char *str, int n);
        int mvaddnstr(int y, int x, in TSingleByteString txt, int n);
        //int mvaddstr(int y, int x, const char *str);
        int mvaddstr(int y, int x, in TSingleByteString txt);
        //int mvgetnstr(int y, int x, char *str, int n);
        int mvgetnstr(int y, int x, ref TSingleByteString str, int count);
        //int mvgetstr(int y, int x, char *str);
        int mvgetstr(int y, int x, ref TSingleByteString str);
        //int mvinnstr(int y, int x, char *str, int n);
        int mvinnstr(int y, int x, ref TSingleByteString str, int n);
        //int mvinsnstr(int y, int x, const char *str, int n);
        int mvinsnstr(int y, int x, in TSingleByteString str, int n);
        //int mvinsstr(int y, int x, const char *str);
        int mvinsstr(int y, int x, in TSingleByteString str);
        //int mvinstr(int y, int x, char *str);
        int mvinstr(int y, int x, ref TSingleByteString str);
        //int mvprintw(int y, int x, const char *fmt, ...);
        int mvprintw(int y, int x, in TSingleByteString str, IntPtr argListPtr);
        //int mvscanw(int y, int x, const char *fmt, ...);
        int mvscanw(int y, int x, ref TSingleByteString format, IntPtr argListPtr);
        //int mvwaddnstr(WINDOW* win, int y, int x, const char* str, int n);
        int mvwaddnstr(IntPtr window, int y, int x, in TSingleByteString str, int n);
        //int mvwaddstr(WINDOW *win, int y, int x, const char *str);
        int mvwaddstr(IntPtr window, int y, int x, in TSingleByteString str);
        //int mvwgetnstr(WINDOW *, int y, int x, char *str, int n);
        int mvwgetnstr(IntPtr window, int y, int x, ref TSingleByteString str, int count);
        //int mvwgetstr(WINDOW *win, int y, int x, char *str);
        int mvwgetstr(IntPtr window, int y, int x, ref TSingleByteString str);
        //int mvwinnstr(WINDOW *win, int y, int x, char *str, int n);
        int mvwinnstr(IntPtr window, int y, int x, ref TSingleByteString str, int n);
        //int mvwinsnstr(WINDOW *win, int y, int x, const char *str, int n);
        int mvwinsnstr(IntPtr window, int y, int x, in TSingleByteString str, int n);
        //int mvwinsstr(WINDOW *win, int y, int x, const char *str);
        int mvwinsstr(IntPtr window, int y, int x, in TSingleByteString str);
        //int mvwinstr(WINDOW *win, int y, int x, char *str);
        int mvwinstr(IntPtr window, int y, int x, ref TSingleByteString str);
        //int mvwprintw(WINDOW *win, int y, int x, const char *fmt, ...);
        int mvwprintw(IntPtr window, int y, int x, in TSingleByteString format, IntPtr varArgListPtr);
        //int mvwscanw(WINDOW *win, int y, int x, const char *fmt, ...);
        int mvwscanw(IntPtr window, int y, int x, ref TSingleByteString format, IntPtr varArgListPtr);
        //int printw(const char *fmt, ...);
        int printw(in TSingleByteString format, IntPtr varArgListPtr);
        //int putp(const char *str);
        int putp(in TSingleByteString str);
        //int putp_sp(SCREEN* sp, const char *str);
        int putp_sp(IntPtr screen, in TSingleByteString str);
        //int scanw(const char *fmt, ...);
        int scanw(ref TSingleByteString format, IntPtr varArgListPtr);
        //int scr_dump(const char *filename);
        int scr_dump(in TSingleByteString filename);
        //int scr_dump_sp(SCREEN* sp, const char *filename);
        int scr_dump_sp(IntPtr screen, in TSingleByteString filename);
        //int scr_init(const char *filename);
        int scr_init(in TSingleByteString filename);
        //int scr_init_sp(SCREEN* sp, const char *filename);
        int scr_init_sp(IntPtr screen, in TSingleByteString filename);
        //int scr_restore(const char *filename);
        int scr_restore(in TSingleByteString filename);
        //int scr_restore_sp(SCREEN* sp, const char *filename);
        int scr_restore_sp(IntPtr screen, in TSingleByteString filename);
        //int scr_set(const char *filename);
        int scr_set(in TSingleByteString filename);
        //int scr_set_sp(SCREEN* sp, const char *filename);
        int scr_set_sp(IntPtr screen, in TSingleByteString filename);
        //char *slk_label(int labnum);
        ref TSingleByteString slk_label(int labnum);
        //char *slk_label_sp(SCREEN* sp, int labnum);
        ref TSingleByteString slk_label_sp(IntPtr screen, int labnum);
        //int slk_set(int labnum, const char *label, int fmt);
        int slk_set(int labnum, in TSingleByteString label, int fmt);
        //int slk_set_sp(SCREEN* sp, int labnum, const char *label, int fmt);
        int slk_set_sp(IntPtr screen, int labnum, in TSingleByteString label, int fmt);
        //char *termname(void);
        ref TSingleByteString termname();
        //char *termname_sp(SCREEN* sp);
        ref TSingleByteString termname_sp(IntPtr screen);
        //int tigetflag(const char *capname);
        int tigetflag(in TSingleByteString capname);
        //int tigetflag_sp(SCREEN* sp, const char *capname);
        int tigetflag_sp(IntPtr screen, in TSingleByteString capname);
        //int tigetnum(const char *capname);
        int tigetnum(in TSingleByteString capname);
        //int tigetnum_sp(SCREEN* sp, const char *capname);
        int tigetnum_sp(IntPtr screen, in TSingleByteString capname);
        //char *tigetstr(const char *capname);
        ref sbyte tigetstr(in TSingleByteString capname);
        //char *tigetstr_sp(SCREEN* sp, const char *capname);
        ref sbyte tigetstr_sp(IntPtr screen, in TSingleByteString capname);
        //int waddnstr(WINDOW *win, const char *str, int n);
        int waddnstr(IntPtr window, in TSingleByteString str, int number);
        //int waddstr(WINDOW *win, const char *str);
        int waddstr(IntPtr window, in TSingleByteString str);
        //int wgetnstr(WINDOW *win, char *str, int n);
        int wgetnstr(IntPtr window, ref TSingleByteString str, int count);
        //int wgetstr(WINDOW *win, char *str);
        int wgetstr(IntPtr window, ref TSingleByteString str);
        //int winnstr(WINDOW *win, char *str, int n);
        int winnstr(IntPtr window, ref TSingleByteString str, int n);
        //int winstr(WINDOW *win, char *str);
        int winstr(IntPtr window, ref TSingleByteString str);
        //int winsnstr(WINDOW *win, const char *str, int n);
        int winsnstr(IntPtr window, in TSingleByteString str, int n);
        //int winsstr(WINDOW *win, const char *str);
        int winsstr(IntPtr window, in TSingleByteString str);
        //int wprintw(WINDOW *win, const char *fmt, ...);
        int wprintw(IntPtr window, in TSingleByteString format, IntPtr varArgListPtr);
        //int wscanw(WINDOW *win, const char *fmt, ...);
        int wscanw(IntPtr window, ref TSingleByteString format, IntPtr varArgListPtr);
    }
}
