using System;
using System.Collections.Generic;
using System.Text;

namespace NCurses.Core.Interop.SmallStr
{
    internal interface INCursesWrapperSmallStr<TSmallStr> : INativeWrapper
    {
        //int addnstr(const char *str, int n);
        int addnstr(in TSmallStr txt, int number);
        //int addstr(const char *str);
        int addstr(in TSmallStr txt);
        //const char * curses_version(void);
        ref TSmallStr curses_version();
        //int define_key(const char *definition, int keycode);
        int define_key(in TSmallStr definition, int keycode);
        //int define_key(SCREEN* sp, const char *definition, int keycode);
        int define_key_sp(IntPtr screen, in TSmallStr definition, int keycode);
        //char erasechar(void);
        TSmallStr erasechar();
        //char erasechar_sp(SCREEN* sp);
        TSmallStr erasechar_sp(IntPtr screen);
        //int getnstr(char *str, int n);
        int getnstr(ref TSmallStr txt, int count);
        //int getstr(char *str);
        int getstr(ref TSmallStr txt);
        //int instr(char *str);
        int innstr(ref TSmallStr str, int n);
        //int insnstr(const char *str, int n);
        int insnstr(in TSmallStr str, int n);
        //int insstr(const char *str);
        int insstr(in TSmallStr str);
        //int instr(char *str);
        int instr(ref TSmallStr str);
        //int key_defined(const char *definition);
        int key_defined(in TSmallStr definition);
        //int key_defined(const char *definition);
        int key_defined_sp(IntPtr screen, in TSmallStr definition);
        //char * keybound(int keycode, int count);
        ref TSmallStr keybound(int keycode, int count);
        //char * keybound_sp(SCREEN* sp, int keycode, int count);
        ref TSmallStr keybound_sp(IntPtr screen, int keycode, int count);
        //char *keyname(int c);
        ref TSmallStr keyname(int c);
        //char *keyname_sp(SCREEN* sp, int c);
        ref TSmallStr keyname_sp(IntPtr screen, int c);
        //char killchar(void);
        TSmallStr killchar();
        //char killchar_sp(SCREEN* sp);
        TSmallStr killchar_sp(IntPtr screen);
        //char *longname(void);
        ref TSmallStr longname();
        //char *longname_sp(SCREEN* sp);
        ref TSmallStr longname_sp(IntPtr screen);
        //int mvaddnstr(int y, int x, const char *str, int n);
        int mvaddnstr(int y, int x, in TSmallStr txt, int n);
        //int mvaddstr(int y, int x, const char *str);
        int mvaddstr(int y, int x, in TSmallStr txt);
        //int mvgetnstr(int y, int x, char *str, int n);
        int mvgetnstr(int y, int x, ref TSmallStr str, int count);
        //int mvgetstr(int y, int x, char *str);
        int mvgetstr(int y, int x, ref TSmallStr str);
        //int mvinnstr(int y, int x, char *str, int n);
        int mvinnstr(int y, int x, ref TSmallStr str, int n);
        //int mvinsnstr(int y, int x, const char *str, int n);
        int mvinsnstr(int y, int x, in TSmallStr str, int n);
        //int mvinsstr(int y, int x, const char *str);
        int mvinsstr(int y, int x, in TSmallStr str);
        //int mvinstr(int y, int x, char *str);
        int mvinstr(int y, int x, ref TSmallStr str);
        //int mvprintw(int y, int x, const char *fmt, ...);
        int mvprintw(int y, int x, in TSmallStr str, IntPtr argListPtr);
        //int mvscanw(int y, int x, const char *fmt, ...);
        int mvscanw(int y, int x, ref TSmallStr format, IntPtr argListPtr);
        //int mvwaddnstr(WINDOW* win, int y, int x, const char* str, int n);
        int mvwaddnstr(IntPtr window, int y, int x, in TSmallStr str, int n);
        //int mvwaddstr(WINDOW *win, int y, int x, const char *str);
        int mvwaddstr(IntPtr window, int y, int x, in TSmallStr str);
        //int mvwgetnstr(WINDOW *, int y, int x, char *str, int n);
        int mvwgetnstr(IntPtr window, int y, int x, ref TSmallStr str, int count);
        //int mvwgetstr(WINDOW *win, int y, int x, char *str);
        int mvwgetstr(IntPtr window, int y, int x, ref TSmallStr str);
        //int mvwinnstr(WINDOW *win, int y, int x, char *str, int n);
        int mvwinnstr(IntPtr window, int y, int x, ref TSmallStr str, int n);
        //int mvwinsnstr(WINDOW *win, int y, int x, const char *str, int n);
        int mvwinsnstr(IntPtr window, int y, int x, in TSmallStr str, int n);
        //int mvwinsstr(WINDOW *win, int y, int x, const char *str);
        int mvwinsstr(IntPtr window, int y, int x, in TSmallStr str);
        //int mvwinstr(WINDOW *win, int y, int x, char *str);
        int mvwinstr(IntPtr window, int y, int x, ref TSmallStr str);
        //int mvwprintw(WINDOW *win, int y, int x, const char *fmt, ...);
        int mvwprintw(IntPtr window, int y, int x, in TSmallStr format, IntPtr varArgListPtr);
        //int mvwscanw(WINDOW *win, int y, int x, const char *fmt, ...);
        int mvwscanw(IntPtr window, int y, int x, ref TSmallStr format, IntPtr varArgListPtr);
        //int printw(const char *fmt, ...);
        int printw(in TSmallStr format, IntPtr varArgListPtr);
        //int putp(const char *str);
        int putp(in TSmallStr str);
        //int putp_sp(SCREEN* sp, const char *str);
        int putp_sp(IntPtr screen, in TSmallStr str);
        //int scanw(const char *fmt, ...);
        int scanw(ref TSmallStr format, IntPtr varArgListPtr);
        //int scr_dump(const char *filename);
        int scr_dump(in TSmallStr filename);
        //int scr_dump_sp(SCREEN* sp, const char *filename);
        int scr_dump_sp(IntPtr screen, in TSmallStr filename);
        //int scr_init(const char *filename);
        int scr_init(in TSmallStr filename);
        //int scr_init_sp(SCREEN* sp, const char *filename);
        int scr_init_sp(IntPtr screen, in TSmallStr filename);
        //int scr_restore(const char *filename);
        int scr_restore(in TSmallStr filename);
        //int scr_restore_sp(SCREEN* sp, const char *filename);
        int scr_restore_sp(IntPtr screen, in TSmallStr filename);
        //int scr_set(const char *filename);
        int scr_set(in TSmallStr filename);
        //int scr_set_sp(SCREEN* sp, const char *filename);
        int scr_set_sp(IntPtr screen, in TSmallStr filename);
        //char *slk_label(int labnum);
        ref TSmallStr slk_label(int labnum);
        //char *slk_label_sp(SCREEN* sp, int labnum);
        ref TSmallStr slk_label_sp(IntPtr screen, int labnum);
        //int slk_set(int labnum, const char *label, int fmt);
        int slk_set(int labnum, in TSmallStr label, int fmt);
        //int slk_set_sp(SCREEN* sp, int labnum, const char *label, int fmt);
        int slk_set_sp(IntPtr screen, int labnum, in TSmallStr label, int fmt);
        //char *termname(void);
        ref TSmallStr termname();
        //char *termname_sp(SCREEN* sp);
        ref TSmallStr termname_sp(IntPtr screen);
        //int tigetflag(const char *capname);
        int tigetflag(in TSmallStr capname);
        //int tigetflag_sp(SCREEN* sp, const char *capname);
        int tigetflag_sp(IntPtr screen, in TSmallStr capname);
        //int tigetnum(const char *capname);
        int tigetnum(in TSmallStr capname);
        //int tigetnum_sp(SCREEN* sp, const char *capname);
        int tigetnum_sp(IntPtr screen, in TSmallStr capname);
        //char *tigetstr(const char *capname);
        ref sbyte tigetstr(in TSmallStr capname);
        //char *tigetstr_sp(SCREEN* sp, const char *capname);
        ref sbyte tigetstr_sp(IntPtr screen, in TSmallStr capname);
        //int waddnstr(WINDOW *win, const char *str, int n);
        int waddnstr(IntPtr window, in TSmallStr str, int number);
        //int waddstr(WINDOW *win, const char *str);
        int waddstr(IntPtr window, in TSmallStr str);
        //int wgetnstr(WINDOW *win, char *str, int n);
        int wgetnstr(IntPtr window, ref TSmallStr str, int count);
        //int wgetstr(WINDOW *win, char *str);
        int wgetstr(IntPtr window, ref TSmallStr str);
        //int winnstr(WINDOW *win, char *str, int n);
        int winnstr(IntPtr window, ref TSmallStr str, int n);
        //int winstr(WINDOW *win, char *str);
        int winstr(IntPtr window, ref TSmallStr str);
        //int winsnstr(WINDOW *win, const char *str, int n);
        int winsnstr(IntPtr window, in TSmallStr str, int n);
        //int winsstr(WINDOW *win, const char *str);
        int winsstr(IntPtr window, in TSmallStr str);
        //int wprintw(WINDOW *win, const char *fmt, ...);
        int wprintw(IntPtr window, in TSmallStr format, IntPtr varArgListPtr);
        //int wscanw(WINDOW *win, const char *fmt, ...);
        int wscanw(IntPtr window, ref TSmallStr format, IntPtr varArgListPtr);
    }
}
